# Copyright (c) 2025, DocPulse and contributors
# For license information, please see license.txt

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.query_builder import Interval
from frappe.query_builder.functions import Now


class DocumentTrackerRenewalLog(Document):
	def validate(self):
		"""Validate and compute total_documents_flagged"""
		# Prevent users from creating renewal logs - only System Manager can create
		# This respects doctype permissions where create is set to 0 for DocPulse roles
		if self.is_new():
			if not frappe.has_permission("Document Tracker Renewal Log", "create"):
				frappe.throw(_("Users cannot create Document Tracker Renewal Log entries. These are system-generated by the scheduler."))
		
		self.total_documents_flagged = len(self.renewal_pending_items) if self.renewal_pending_items else 0
		
		# Note: Multiple logs per day are allowed to track changes over time
		# The scheduler creates a new log on each run if documents require renewal

	def on_submit(self):
		"""Handle submission - group notifications by owner_person and department"""
		# Group notifications by owner_person
		owner_groups = {}
		department_groups = {}
		
		for item in self.renewal_pending_items:
			# Group by owner
			if item.owner_person:
				if item.owner_person not in owner_groups:
					owner_groups[item.owner_person] = []
				owner_groups[item.owner_person].append(item)
			
			# Group by department (if available from document)
			try:
				doc = frappe.get_doc("Document Tracker List", item.document)
				if doc.department:
					if doc.department not in department_groups:
						department_groups[doc.department] = []
					department_groups[doc.department].append(item)
			except frappe.DoesNotExistError:
				# Document might have been deleted, skip
				continue
		
		# Send notifications grouped by owner
		for owner, items in owner_groups.items():
			self.send_owner_notification(owner, items)
		
		# Send notifications grouped by department
		for department, items in department_groups.items():
			self.send_department_notification(department, items)
		
		# Log success (msgprint is for UI, not suitable for scheduled tasks)
		frappe.logger().info(
			_("Renewal log {0} submitted. Notifications sent to owners and departments.").format(self.name)
		)

	def send_owner_notification(self, owner, items):
		"""Send notification digest to owner"""
		# Create notification for the owner
		message = _("You have {0} document(s) requiring renewal attention.").format(len(items))
		
		# Create a notification
		frappe.publish_realtime(
			event="notification",
			message={
				"type": "alert",
				"title": _("Document Renewal Alert"),
				"message": message,
				"indicator": "orange"
			},
			user=owner
		)
		
		# Also create a ToDo for tracking
		try:
			todo = frappe.get_doc({
				"doctype": "ToDo",
				"allocated_to": owner,
				"description": message + " Check Document Tracker Renewal Log: " + self.name,
				"reference_type": "Document Tracker Renewal Log",
				"reference_name": self.name,
				"priority": "High",
				"status": "Open"
			})
			todo.insert(ignore_permissions=True)
		except Exception as e:
			frappe.log_error(f"Error creating ToDo for owner {owner}: {str(e)}")

	def send_department_notification(self, department, items):
		"""Send notification digest to department"""
		# Get department head or all users in department
		# For now, just log - can be extended with actual department notification logic
		frappe.logger().info(f"Department {department} has {len(items)} documents requiring renewal attention")
	
	@staticmethod
	def clear_old_logs(days=90):
		"""
		Clear old Document Tracker Renewal Log records.
		This method is called by Log Settings to automatically clean up old logs.
		
		Args:
			days: Number of days to retain logs. Logs older than this will be deleted.
		"""
		table = frappe.qb.DocType("Document Tracker Renewal Log")
		frappe.db.delete(table, filters=(table.modified < (Now() - Interval(days=days))))
